# Generated by Django 3.2.3 on 2021-05-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='25.05.2021'),
            preserve_default=False,
        ),
    ]
